from pybeamline.algorithms.discovery.activity_entity_relation_miner_lossy_counting import activity_entity_relations_miner_lossy_counting
from pybeamline.algorithms.discovery.dfg_miner import simple_dfg_miner
from pybeamline.algorithms.discovery.heuristics_miner_lossy_counting import heuristics_miner_lossy_counting
from pybeamline.algorithms.discovery.heuristics_miner_lossy_counting_budget import heuristics_miner_lossy_counting_budget
from pybeamline.algorithms.discovery.temporal_profile import temporal_profile_discovery_mapper

