#from pybeamline.algorithms.conformance.behavioral_conformance import behavioral_conformance
#from pybeamline.algorithms.conformance.behavioral_conformance import mine_behavioral_model_from_stream
#import pybeamline.algorithms.conformance.MultiperspectiveConformace.MP_Declare_Model